name = "CDSAPI"
uuid = "8a7b9de3-9c00-473e-88b4-7eccd7ef2fea"
authors = ["Micky Yun Chan <michan@redhat.com> and contributors"]
version = "0.2.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
HTTP = "0.8, 0.9, 1"
JSON = "0.21"
julia = "1.3"

[extras]
GRIB = "b16dfd50-4035-11e9-28d4-9dfe17e6779b"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[targets]
test = ["Test", "GRIB", "ZipFile", "NetCDF", "Tar", "GZip"]
