name = "CDSAPI"
uuid = "8a7b9de3-9c00-473e-88b4-7eccd7ef2fea"
authors = ["Micky Yun Chan <michan@redhat.com> and contributors"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
HTTP = "0.8"
JSON = "0.21"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
GRIB = "b16dfd50-4035-11e9-28d4-9dfe17e6779b"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"

[targets]
test = ["Test", "GRIB", "ZipFile", "NetCDF"]
